
server:
  port: 8084
  
spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8085  
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri:
          lb://USER-SERVICE
        predicates:
        - Path=/users/**
        
      - id: HOTEL-SERVICE
        uri:
          lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**
        
      - id: RATING-SERVICES
        uri:
          lb://RATING-SERVICES
        predicates:
        - Path=/ratings/**

