server:
  port: 8081

spring:
  
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/usermicroservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8085
   
   #Spring Security configuartion with OKTA auth
   
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  https://dev-14541509.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa8kafc4jcgV8l2a5d7                           #check in application in ockta client and wiil be there
            client-secret: fQ7NsT5L-Ei8xZujzZYMTlDtPBlF9CFe53JkGKZY

        provider:
          okta:
            issuer-uri:  https://dev-14541509.okta.com/oauth2/default

    
    
# Configuration for circuit breaker

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true   #this check health of application with the help of actuatuter
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s
        
 
 
# This is an Okta authentication
        
okta:
  oauth2:
    issuer: https://dev-14541509.okta.com/oauth2/default      # this will give us from okta web side check API security→ ApI → default → issuer
    audience: api://default

        
        